### PR TITLE
Always install latest compatible Jade

### PR DESCRIPTION
**Pull request by julien-f**

### CODE REVIEW

**Comment by julien-f** [comment]
Up.

**Comment by redhotvengeance** [comment]
@julien-f Got caught up in some other things and this slip by. Merged.

**Comment by julien-f** [comment]
Thanks!

No problem, it was just a friendly reminder :)

**Comment by redhotvengeance** [comment]
@julien-f Thanks for that! v0.2.2 has been published to npm.

**Comment by julien-f** [comment]
Great!

**Pull request merged**
